# SPDX-License-Identifier: Apache-2.0
name: GraphCap
services:
  caption:
    build:
      context: ./server
      dockerfile: ./Dockerfile.server
    ports:
      - 32100:32100
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - graphcap_cache:/cache/HF_HOME
      - ./local/cache:/cache/local_cache
    environment:
      - HF_HOME=/cache/HF_HOME
      - ODR_TEXT_MODEL=${ODR_TEXT_MODEL:-Qwen/Qwen2.5-14B-Instruct-GPTQ-Int8}
      - ODR_VISION_MODEL=${ODR_VISION_MODEL:-mistral-community/pixtral-12b}
      - HOST_PLATFORM=${HOST_PLATFORM:-linux}
    develop:
      watch:
        - action: sync
          path: ./GraphCap
          target: /app/GraphCap

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: graphcap
      POSTGRES_PASSWORD: graphcap
      POSTGRES_DB: graphcap
    ports:
      - "35432:5432"
    volumes:
      - graphcap_data:/var/lib/postgresql/data

volumes:
  graphcap_data:
  graphcap_cache:
