# SPDX-License-Identifier: Apache-2.0
version: '3'

tasks:
  build:
    cmds:
      - docker compose build

  rebuild:
    cmds:
      - docker compose up --build

  run:
    cmds:
      - docker compose up

  watch:
    cmds:
      - docker compose  up --build --watch
  logs:
    cmds:
      - docker compose  logs -f
  stop:
    cmds:
      - docker compose down

