# SPDX-License-Identifier: Apache-2.0
name: GraphCap
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: graphcap
      POSTGRES_PASSWORD: graphcap
      POSTGRES_DB: graphcap
    ports:
      - "35432:5432"
    volumes:
      - graphcap_data:/var/lib/postgresql/data

volumes:
  graphcap_data:
