[project]
name = "GraphCap"
version = "0.0.1"
description = "GraphCap"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.3.0",
    "click>=8.1.8",
    "datasets>=3.2.0",
    "fastapi>=0.115.6",
    "hf-transfer>=0.1.9",
    "httpx>=0.28.1",
    "openai>=1.59.9",
    "outlines>=0.1.11",
    "pydantic>=2.10.5",
    "python-dotenv>=1.0.1",
    "python-multipart>=0.0.20",
    "qwen-vl-utils[decord]>=0.0.8",
    "termcolor>=2.5.0",
    "torch>=2.5.1",
    "torchvision>=0.20.1",
    "transformers>=4.48.1",
    "uvicorn>=0.34.0",
    "vllm>=0.6.6.post1",
]


[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "ruff>=0.9.1",
]
