# SPDX-License-Identifier: Apache-2.0
name: graphcap
services:
  gcap_server:
    container_name: gcap_server
    build:
      context: ../
      dockerfile: server/Dockerfile.server
    ports:
      - 32100:32100

    volumes:
      - ./local/cache:/cache/local_cache
      - ./provider.config.toml:/app/provider.config.toml
      - ../graphcap:/app/graphcap
      - ../pyproject.toml:/app/pyproject.toml
      - ../uv.lock:/app/uv.lock
    environment:
      - HF_HOME=/cache/HF_HOME
      - ODR_TEXT_MODEL=${ODR_TEXT_MODEL:-Qwen/Qwen2.5-14B-Instruct-GPTQ-Int8}
      - ODR_VISION_MODEL=${ODR_VISION_MODEL:-mistral-community/pixtral-12b}
      - HOST_PLATFORM=${HOST_PLATFORM:-linux}
      - PYTHONPATH=/app
    env_file:
      - ../.env
    develop:
      watch:
        - action: sync+restart
          path: ../graphcap
          target: /app/graphcap
          ignore:
            - "**/__pycache__"
            - "**/*.pyc"
        - action: sync
          path: ../server/server
          target: /app/server/server
          ignore:
            - "**/__pycache__"
            - "**/*.pyc"
    networks:
      - graphcap


  gcap_postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: graphcap
      POSTGRES_PASSWORD: graphcap
      POSTGRES_DB: graphcap
    ports:
      - "35432:5432"
    volumes:
      - gcap_data:/var/lib/postgresql/data
    networks:
      - graphcap


volumes:
  gcap_data:

networks:
  graphcap:
    driver: bridge
