# SPDX-License-Identifier: Apache-2.0
name: graphcap
services:
  gcap_server:
    container_name: gcap_server
    build:
      context: ../
      dockerfile: server/Dockerfile.server
    ports:
      - 32100:32100
    volumes:
      - ../lib/graphcap:/app/lib/graphcap
      - ../server:/app/server
      - ../config:/workspace/config
      - ../.local:/workspace/.local
      - ../datasets:/workspace/datasets
    environment:
      - HOST_PLATFORM=${HOST_PLATFORM:-linux}
      - PYTHONPATH=/app/server
      - DATABASE_URL=postgresql+asyncpg://graphcap:graphcap@gcap_postgres:5432/graphcap
    env_file:
      - ../.env
    develop:
      watch:
        - action: sync+restart
          path: ../lib/graphcap
          target: /app/lib/graphcap
          ignore:
            - "**/__pycache__"
            - "**/*.pyc"
        - action: sync
          path: ../server/server
          target: /app/server/server
          ignore:
            - "**/__pycache__"
            - "**/*.pyc"
    networks:
      - graphcap
    depends_on:
      gcap_postgres:
        condition: service_healthy

  gcap_postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: graphcap
      POSTGRES_PASSWORD: graphcap
      POSTGRES_DB: graphcap
    ports:
      - "35432:5432"
    volumes:
      - graphcap_server_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U graphcap"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - graphcap

volumes:
  graphcap_server_db:

networks:
  graphcap:
    driver: bridge
