# SPDX-License-Identifier: Apache-2.0
version: '3'


tasks:
  vllm-pixtral:
    cmds:
      - >
        docker run
        --rm
        --runtime nvidia
        --gpus all
        -p 12434:12434
        -v /mnt/drive/models:/root/.cache/huggingface
        --env "HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}"
        vllm/vllm-openai:latest
        --port 12434
        --model mistralai/Pixtral-12B-2409
        --tokenizer_mode mistral
        --config_format mistral
        --load_format mistral
        --tool-call-parser mistral
        --max-model-len 16434
        --enable-auto-tool-choice
        --served-model-name vision-worker
  stop-vllm-pixtral:
    cmds:
      - docker stop vllm-pixtral
  vllm-qwen:
    description: "Start the Qwen2.5-VL-7B-Instruct model"
    dir: ./config/provider_helpers
    cmds:
      - sh qwen2_5vl.sh
