# SPDX-License-Identifier: Apache-2.0
name: Build Client Images

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  CLIENT_IMAGE_NAME: ${{ github.repository }}/client

jobs:
  client-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build test container
        uses: docker/build-push-action@v6
        with:
          context: ./client
          file: ./client/Dockerfile.client
          load: true
          tags: graphcap-client:test
          target: test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run checks
        run: |
          docker run --rm graphcap-client:test pnpm check
          docker run --rm graphcap-client:test pnpm lint

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Client Docker metadata
        id: meta-client
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.CLIENT_IMAGE_NAME }}

      - name: Build Client Docker image
        id: build-client
        uses: docker/build-push-action@v6
        with:
          context: ./client
          file: ./client/Dockerfile.client
          push: false
          tags: ${{ steps.meta-client.outputs.tags }}
          labels: ${{ steps.meta-client.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max