# SPDX-License-Identifier: Apache-2.0
name: GraphCap Library CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'graphcap/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'setup.py'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'graphcap/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'setup.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install Ruff
        run: pip install ruff
      - name: Run Ruff
        run: |
          ruff check ./graphcap --output-format=github
          ruff format --check ./graphcap

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[test]"
      - name: Run tests
        run: |
          pytest tests/ -v -m "not integration and not server" --cov=graphcap 